# Generated by Django 2.2.12 on 2020-07-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPlanningRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_assigned', models.DateField()),
                ('active_run', models.BooleanField()),
                ('area', models.FloatField()),
            ],
            options={
                'db_table': 'field_planning_run',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Type')),
            ],
        ),
    ]
