  version: '3'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=test_db
        - POSTGRES_USER=ed_core_data_dev
        - POSTGRES_PASSWORD=
      ports:
      - 6543:6543
    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db

#  version: '3'
#
#  services:
#    web:
#      build: .
#      volumes:
#        - .:/code
#      ports:
#        - "8000:8000"
#      depends_on:
#        - djangoDB
#      links:
#        - djangoDB
#      deploy:
#        resources:
#          limits:
#            cpus: '1'
#            memory: 2048M
#
#    djangoDB:
#      image: postgres
#      environment:
#        - POSTGRES_DB=db1
#        - POSTGRES_USER=test
#        - POSTGRES_PASSWORD=test
#      ports:
#        - "5406:5432"
#      deploy:
#        resources:
#          limits:
#            cpus: '1'
#            memory: 1024M