# Generated by Django 2.2.12 on 2020-07-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='name_text',
            new_name='name_class',
        ),
        migrations.RenameField(
            model_name='schools',
            old_name='name_text',
            new_name='name_school',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name_text',
            new_name='name_student',
        ),
    ]
