# Generated by Django 2.2.12 on 2020-07-16 07:40

from django.db import migrations
import random
import datetime

def create_data_students(apps, schema_editor):
    Students = apps.get_model("school", "Students")
    Classes = apps.get_model("school", "Classes")
    name = ("Super", "Retarded", "Great", "Sexy", "Vegan", "Brave", "Shy", "Cool", "Poor", "Rich", "Fast", "Gummy", "Yummy", "Masked", "Unusual", "American", "Bisexual", "MLG", "Mlg", "lil", "Lil")
    sex = ("Male", "Female", "Other")
    list_student = []
    class_of_student = Classes.objects.get(pk=1)
    for i in range(1000):
        student = Students(sex=random.choice(sex), name_student=random.choice(name), birth_date=datetime.datetime(1996, 5, 17), classes=class_of_student)
        list_student.append(student)
    Students.objects.bulk_create(list_student)
       



class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200716_0740'),
    ]

    operations = [
        migrations.RunPython(create_data_students),
    ]